### ISSUE TITLE
Does push notification service provides API to integrate new applications?

### ISSUE THREAD

**Issue by RossWhitlock** [Truepush-tool/Push-Service-for-WordPress#4]
I am using a push service for my website developed with Angular JS. Now I want to add new applications to the system using API can this be possible?

**Comment by Truepush-tool** [comment]
Absolutely, Truepush provides API modules for many functions. 

To start using Truepush APIs. Find the authorisation token in your settings

**Your project -> settings -> Authentication Token**

You can check the available API on the website page under the drop line of platforms or else simply [click here](https://www.truepush.com/api).
