### ISSUE TITLE
I can't see the opt-in on the website after integrating the plugin?

### ISSUE THREAD

**Issue by Ramyaa-98** [Truepush-tool/Push-Service-for-WordPress#5]
I have integrated the WordPress plugin into the Website but am unable see the subscription opt-in on the website. let me the know the further steps or procedure to make push notification work.

**Comment by Truepush-tool** [comment]
We are here to assist you in any aspect of integrating web push service into your website. 

Firstly I recommend you check the sw.js file on your website to check if the push service is integrated perfectly. In another case, you can uninstall the plugin and reinstall it. 

If still the opt-in is enabled on the website, go to settings in the [Truepush dashboard](https://www.truepush.com/) and choose the opt-in styles and content. 

You can check the [Opt-in settings](https://www.truepush.com/blog/opt-in-settings/) blog to know more details.
